# Generated by Django 3.1.2 on 2020-11-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
